version: '3'
services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: maino-postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maino"]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - '5432:5432'
    expose:
      - 5432

  app:
    build: .
    container_name: maino-web
    command: "./bin/rails server -b 0.0.0.0"
    env_file:
      - ./.env
    volumes:
      - app-storage:/rails/storage
      - uploads:/rails/app/uploads
      - rubygems:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    expose:
      - 3000

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: maino-worker
    env_file:
      - ./.env
    volumes:
      - uploads:/rails/app/uploads
    depends_on:
      redis:
        condition: service_healthy
    ports: [ ]

  redis:
    image: redis:6.2-alpine
    container_name: maino-redis
    restart: 'always'
    ports:
      - '6380:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: {}
  app-storage: {}
  rubygems: {}
  uploads: {}